menu:
  Home: /
  Archives: /archives
  Tags: /tags
  About: https://weiming.me

# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: true
disqus_shortname: Weiming

# google analytics
googleTrackId: UA-77129198-1

# whether to show read more button when showing article in excerpt in main page
read_more_btn: true
