menu:
  Home: /
  Archives: /archives
  Tags: /tags
  About: http://zhuangweiming.me

# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: true
disqus_shortname: Weiming

# google analytics
googleTrackId: UA-77129198-1
